### ISSUE TITLE
[Bug] 缺失 Sub-Store 调试日志功能和 http-meta 组件集成

### ISSUE THREAD

**Issue by qixing-jk** [pompurin404/mihomo-party#303]
### Verify steps

- [x] 我已在标题简短的描述了我所遇到的问题
- [x] 我已在 [Issue Tracker](./?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
- [x] 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
- [x] 这是 GUI 程序的问题，而不是内核程序的问题
- [x] 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
- [x] 我已经使用最新的测试版本测试过，问题依旧存在

### 操作系统

Windows

### 系统版本

Windows 11 Pro

### 发生问题 mihomo-party 版本

v1.5.6

### 描述

1. 本地无法找到mihomo party的日志和脚本调试输出

> [sub-store作者回复： mihomo-party 如何查看脚本调试日志请咨询 mihomo-party](https://github.com/sub-store-org/Sub-Store/issues/368#issuecomment-2451409270)

2. sub-store许多脚本的依赖项 [http-meta](https://github.com/xream/http-meta?tab=readme-ov-file) 未找到，因为依赖此功能的脚本无法正常运行，默认参数的http-meta本地端口也并未打开，故认为应该是没有集成此功能

### 重现方式

1. 正常使用和调试sub-store脚本，尝试寻找调试信息
2. 并尝试依赖http-meta的脚本，运行没有效果

**Comment by xishang0128** [comment]
@qixing-jk 1,使用终端运行

2,另外起一个内核客户端可能会导致流量异常,所以不内置

**Comment by qixing-jk** [comment]
> [@qixing-jk](https://github.com/qixing-jk) 1,使用终端运行
> 
> 2,另外起一个内核客户端可能会导致流量异常,所以不内置

能否给出更加详细的说明，不是很懂要怎么操作
